sudo: false
language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 3.3
env:
  - FLASK=0.12
  - $FLASK-WTF=0.15
install:
  - pip install -q Flask==$FLASK
  - pip install -q Flask-WTF==$FLASK-WTF
  - pip install coveralls
script:
  - "python -m unittest discover -s tests"
after_success:
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: change